export const items = [
  {
    key: "C001",
    tipo: "contrato",
    titulo: "Contrato de Prestação de Serviços de TI",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Termos e condições gerais",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Política de segurança da informação",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Detalhes de pagamento",
    subtipo: "Serviços de Consultoria",
    colecao: "Contratos 2024",
    classe: "Digital",
    subclasse: "Serviços de Tecnologia",
    "data Documento": "2024-06-20",
    assunto: "Acordo de Prestação de Serviços",
    clausulas: ["1. Objeto do contrato", "2. Responsabilidades das partes"],
    observacao: "Este contrato entra em vigor imediatamente.",
  },
  {
    key: "L001",
    tipo: "livro",
    "tombo do livro": "TOM001",
    titulo: "A Arte da Programação",
    autor: "Ana Oliveira",
    "ano de Publicacao": 2015,
    assunto: "Programação e Desenvolvimento de Software",
  },
  {
    key: "CAP001",
    tipo: "capítulo",
    livro: "História da Matemática",
    titulo: "Contribuições de Euclides para a Geometria",
    autor: "José Santos",
    paginacao: "45-67",
    assunto: "Matemática e História",
  },
  {
    key: "C002",
    tipo: "contrato",
    titulo: "Contrato de Fornecimento de Equipamentos",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Especificações técnicas dos equipamentos",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Condições de entrega",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Termos de garantia",
    subtipo: "Fornecimento de Hardware",
    colecao: "Contratos 2023",
    classe: "Físico",
    subclasse: "Equipamentos de Informática",
    "data Documento": "2023-03-15",
    assunto: "Contrato de Compra e Venda",
    clausulas: ["1. Objeto do contrato", "2. Condições de pagamento"],
    observacao: "Este contrato é válido por um ano.",
  },
  {
    key: "L002",
    tipo: "livro",
    "tombo do livro": "TOM002",
    titulo: "A História da Filosofia",
    autor: "Pedro Almeida",
    "ano de Publicacao": 2010,
    assunto: "Filosofia e Pensamento Crítico",
  },
  {
    key: "CAP002",
    tipo: "capítulo",
    livro: "Introdução à Economia",
    titulo: "Teoria da Oferta e Demanda",
    autor: "Marta Silva",
    paginacao: "112-135",
    assunto: "Economia e Mercado",
  },
  {
    key: "C003",
    tipo: "contrato",
    titulo: "Contrato de Locação de Imóvel",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Detalhes do imóvel e condições de uso",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Responsabilidades do locatário",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Prazo de vigência do contrato",
    subtipo: "Residencial",
    colecao: "Contratos 2022",
    classe: "Físico",
    subclasse: "Locação de Imóveis",
    "data Documento": "2022-09-10",
    assunto: "Locação Residencial",
    clausulas: ["1. Objeto do contrato", "2. Obrigações das partes"],
    observacao: "Este contrato pode ser renovado automaticamente.",
  },
  {
    key: "L003",
    tipo: "livro",
    "tombo do livro": "TOM003",
    titulo: "A Viagem do Elefante",
    autor: "José Saramago",
    "ano de Publicacao": 2008,
    assunto: "Literatura Contemporânea",
  },
  {
    key: "CAP003",
    tipo: "capítulo",
    livro: "Introdução à Psicologia",
    titulo: "Teorias da Personalidade",
    autor: "Fernanda Costa",
    paginacao: "78-95",
    assunto: "Psicologia e Comportamento Humano",
  },
  {
    key: "C004",
    tipo: "contrato",
    titulo: "Contrato de Consultoria Jurídica",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Serviços a serem prestados pelo consultor",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Honorários e forma de pagamento",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Confidencialidade e sigilo das informações",
    subtipo: "Consultoria Especializada",
    colecao: "Contratos 2023",
    classe: "Digital",
    subclasse: "Serviços Jurídicos",
    "data Documento": "2023-07-03",
    assunto: "Assessoria Jurídica",
    clausulas: ["1. Objeto do contrato", "2. Responsabilidades das partes"],
    observacao: "Este contrato é confidencial.",
  },
  {
    key: "L004",
    tipo: "livro",
    "tombo do livro": "TOM004",
    titulo: "Introdução à Teoria dos Grafos",
    autor: "Luís Mendes",
    "ano de Publicacao": 2013,
    assunto: "Matemática e Computação",
  },
  {
    key: "CAP004",
    tipo: "capítulo",
    livro: "Química Orgânica Avançada",
    titulo: "Reações de Substituição Nucleofílica",
    autor: "Carlos Oliveira",
    paginacao: "34-56",
    assunto: "Química e Reações Orgânicas",
  },
  {
    key: "C005",
    tipo: "contrato",
    titulo: "Contrato de Manutenção de Equipamentos Médicos",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Serviços de manutenção preventiva e corretiva",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Condições de garantia dos serviços",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Horários de atendimento e suporte",
    subtipo: "Serviços de Saúde",
    colecao: "Contratos 2022",
    classe: "Físico",
    subclasse: "Manutenção de Equipamentos",
    "data Documento": "2022-04-18",
    assunto: "Serviços Médicos",
    clausulas: ["1. Objeto do contrato", "2. Responsabilidades das partes"],
    observacao: "Este contrato inclui serviço de plantão.",
  },
  {
    key: "L005",
    tipo: "livro",
    "tombo do livro": "TOM005",
    titulo: "O Poder do Hábito",
    autor: "Charles Duhigg",
    "ano de Publicacao": 2012,
    assunto: "Psicologia e Mudança Comportamental",
  },
  {
    key: "CAP005",
    tipo: "capítulo",
    livro: "Fundamentos da Biologia Celular",
    titulo: "Organelas Celulares",
    autor: "Ana Martins",
    paginacao: "23-41",
    assunto: "Biologia e Células",
  },
  {
    key: "C006",
    tipo: "contrato",
    titulo: "Contrato de Desenvolvimento de Software",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Especificações técnicas do projeto",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Cronograma de entregas",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Termos de manutenção e suporte",
    subtipo: "Desenvolvimento de Aplicações",
    colecao: "Contratos 2023",
    classe: "Digital",
    subclasse: "Desenvolvimento de Software",
    "data Documento": "2023-10-05",
    assunto: "Desenvolvimento de Sistemas",
    clausulas: ["1. Objeto do contrato", "2. Prazo de desenvolvimento"],
    observacao: "Este contrato inclui treinamento dos usuários finais.",
  },
  {
    key: "L006",
    tipo: "livro",
    "tombo do livro": "TOM006",
    titulo: "O Código Da Vinci",
    autor: "Dan Brown",
    "ano de Publicacao": 2003,
    assunto: "Mistério e Suspense",
  },
  {
    key: "CAP006",
    tipo: "capítulo",
    livro: "História da Arte",
    titulo: "Renascimento Italiano",
    autor: "Mário Costa",
    paginacao: "98-115",
    assunto: "Arte e História da Cultura",
  },
  {
    key: "C007",
    tipo: "contrato",
    titulo: "Contrato de Parceria Comercial",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Objetivos da parceria e metas comerciais",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Responsabilidades de cada parte",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Divisão de lucros e prejuízos",
    subtipo: "Parceria Estratégica",
    colecao: "Contratos 2024",
    classe: "Digital",
    subclasse: "Parcerias Empresariais",
    "data Documento": "2024-01-15",
    assunto: "Acordo Comercial",
    clausulas: ["1. Objeto do contrato", "2. Termos financeiros"],
    observacao: "Este contrato é válido por dois anos.",
  },
  {
    key: "L007",
    tipo: "livro",
    "tombo do livro": "TOM007",
    titulo: "A Revolução dos Bichos",
    autor: "George Orwell",
    "ano de Publicacao": 1945,
    assunto: "Literatura Clássica",
  },
  {
    key: "CAP007",
    tipo: "capítulo",
    livro: "Economia Internacional",
    titulo: "Teoria das Vantagens Comparativas",
    autor: "Rui Santos",
    paginacao: "77-91",
    assunto: "Economia Global",
  },
  {
    key: "C008",
    tipo: "contrato",
    titulo: "Contrato de Licenciamento de Software",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Condições de uso do software",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Restrições e direitos de propriedade",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Atualizações e suporte técnico",
    subtipo: "Licenciamento de Produtos",
    colecao: "Contratos 2023",
    classe: "Digital",
    subclasse: "Licenciamento de Software",
    "data Documento": "2023-09-25",
    assunto: "Licenciamento de Tecnologia",
    clausulas: ["1. Objeto do contrato", "2. Condições de pagamento"],
    observacao: "Este contrato é renovável anualmente.",
  },
  {
    key: "L008",
    tipo: "livro",
    "tombo do livro": "TOM008",
    titulo: "O Nome da Rosa",
    autor: "Umberto Eco",
    "ano de Publicacao": 1980,
    assunto: "Romance Histórico",
  },
  {
    key: "CAP008",
    tipo: "capítulo",
    livro: "Sociologia Urbana",
    titulo: "Teoria dos Espaços Urbanos",
    autor: "Maria Fernandes",
    paginacao: "45-67",
    assunto: "Sociologia e Urbanismo",
  },
  {
    key: "C009",
    tipo: "contrato",
    titulo: "Contrato de Seguro de Vida",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Coberturas e exclusões do seguro",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Condições para acionar o seguro",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Beneficiários e forma de pagamento",
    subtipo: "Seguro Pessoal",
    colecao: "Contratos 2022",
    classe: "Físico",
    subclasse: "Seguros de Vida",
    "data Documento": "2022-11-30",
    assunto: "Proteção e Segurança",
    clausulas: ["1. Objeto do contrato", "2. Direitos e obrigações das partes"],
    observacao: "Este contrato possui cláusulas específicas para invalidez.",
  },
  {
    key: "L009",
    tipo: "livro",
    "tombo do livro": "TOM009",
    titulo: "1984",
    autor: "George Orwell",
    "ano de Publicacao": 1949,
    assunto: "Ficção Distópica",
  },
  {
    key: "CAP009",
    tipo: "capítulo",
    livro: "Introdução à Física Moderna",
    titulo: "Teoria da Relatividade",
    autor: "Carlos Mendonça",
    paginacao: "23-38",
    assunto: "Física e Teorias Modernas",
  },
  {
    key: "C010",
    tipo: "contrato",
    titulo: "Contrato de Compra e Venda de Veículo",
    link1: "https://example.com/contrato1",
    "descricao Link1": "Descrição do veículo e condições de pagamento",
    link2: "https://example.com/contrato2",
    "descricao Link2": "Obrigações do vendedor e comprador",
    link3: "https://example.com/contrato3",
    "descricao Link3": "Transferência de documentação",
    subtipo: "Compra e Venda de Bens",
    colecao: "Contratos 2022",
    classe: "Físico",
    subclasse: "Compra e Venda de Veículos",
    "data Documento": "2022-08-12",
    assunto: "Transação Comercial",
    clausulas: ["1. Objeto do contrato", "2. Forma de pagamento"],
    observacao: "Este contrato é válido até a transferência do veículo.",
  },
  {
    key: "L010",
    tipo: "livro",
    "tombo do livro": "TOM010",
    titulo: "O Hobbit",
    autor: "J.R.R. Tolkien",
    "ano de Publicacao": 1937,
    assunto: "Fantasia e Aventura",
  },
  {
    key: "CAP010",
    tipo: "capítulo",
    livro: "Genética Molecular",
    titulo: "Estrutura do DNA",
    autor: "Ana Maria",
    paginacao: "12-31",
    assunto: "Genética e Biologia Molecular",
  },
];
