export const items = [
  {
    key: 1,
    titulo: "Contrato 1",
    tipoDocumental: "Contrato",
    subtipoDocumental: "1",
    colecao: "A",
    classe: "X",
    subclasse: "Z",
  },
  {
    key: 2,
    titulo: "Capítulo 2",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "2",
    colecao: "B",
    classe: "Y",
    subclasse: "W",
  },
  {
    key: 3,
    titulo: "Livro 3",
    tipoDocumental: "Livro",
    subtipoDocumental: "3",
    colecao: "C",
    classe: "Z",
    subclasse: "X",
  },
  {
    key: 4,
    titulo: "Contrato 4",
    tipoDocumental: "Contrato",
    subtipoDocumental: "4",
    colecao: "D",
    classe: "W",
    subclasse: "Y",
  },
  {
    key: 5,
    titulo: "Capítulo 5",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "5",
    colecao: "E",
    classe: "X",
    subclasse: "Z",
  },
  {
    key: 6,
    titulo: "Livro 6",
    tipoDocumental: "Livro",
    subtipoDocumental: "6",
    colecao: "F",
    classe: "Y",
    subclasse: "W",
  },
  {
    key: 7,
    titulo: "Contrato 7",
    tipoDocumental: "Contrato",
    subtipoDocumental: "7",
    colecao: "G",
    classe: "Z",
    subclasse: "X",
  },
  {
    key: 8,
    titulo: "Capítulo 8",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "8",
    colecao: "H",
    classe: "W",
    subclasse: "Y",
  },
  {
    key: 9,
    titulo: "Livro 9",
    tipoDocumental: "Livro",
    subtipoDocumental: "9",
    colecao: "I",
    classe: "X",
    subclasse: "Z",
  },
  {
    key: 10,
    titulo: "Contrato 10",
    tipoDocumental: "Contrato",
    subtipoDocumental: "10",
    colecao: "J",
    classe: "Y",
    subclasse: "W",
  },
  {
    key: 11,
    titulo: "Capítulo 11",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "11",
    colecao: "K",
    classe: "Z",
    subclasse: "X",
  },
  {
    key: 12,
    titulo: "Livro 12",
    tipoDocumental: "Livro",
    subtipoDocumental: "12",
    colecao: "L",
    classe: "W",
    subclasse: "Y",
  },
  {
    key: 13,
    titulo: "Contrato 13",
    tipoDocumental: "Contrato",
    subtipoDocumental: "13",
    colecao: "M",
    classe: "X",
    subclasse: "Z",
  },
  {
    key: 14,
    titulo: "Capítulo 14",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "14",
    colecao: "N",
    classe: "Y",
    subclasse: "W",
  },
  {
    key: 15,
    titulo: "Livro 15",
    tipoDocumental: "Livro",
    subtipoDocumental: "15",
    colecao: "O",
    classe: "Z",
    subclasse: "X",
  },
  {
    key: 16,
    titulo: "Contrato 16",
    tipoDocumental: "Contrato",
    subtipoDocumental: "16",
    colecao: "P",
    classe: "W",
    subclasse: "Y",
  },
  {
    key: 17,
    titulo: "Capítulo 17",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "17",
    colecao: "Q",
    classe: "X",
    subclasse: "Z",
  },
  {
    key: 18,
    titulo: "Livro 18",
    tipoDocumental: "Livro",
    subtipoDocumental: "18",
    colecao: "R",
    classe: "Y",
    subclasse: "W",
  },
  {
    key: 19,
    titulo: "Contrato 19",
    tipoDocumental: "Contrato",
    subtipoDocumental: "19",
    colecao: "S",
    classe: "Z",
    subclasse: "X",
  },
  {
    key: 20,
    titulo: "Capítulo 20",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "20",
    colecao: "T",
    classe: "W",
    subclasse: "Y",
  },
  {
    key: 21,
    titulo: "Livro 21",
    tipoDocumental: "Livro",
    subtipoDocumental: "21",
    colecao: "U",
    classe: "X",
    subclasse: "Z",
  },
  {
    key: 22,
    titulo: "Contrato 22",
    tipoDocumental: "Contrato",
    subtipoDocumental: "22",
    colecao: "V",
    classe: "Y",
    subclasse: "W",
  },
  {
    key: 23,
    titulo: "Capítulo 23",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "23",
    colecao: "W",
    classe: "Z",
    subclasse: "X",
  },
  {
    key: 24,
    titulo: "Livro 24",
    tipoDocumental: "Livro",
    subtipoDocumental: "24",
    colecao: "X",
    classe: "W",
    subclasse: "Y",
  },
  {
    key: 25,
    titulo: "Contrato 25",
    tipoDocumental: "Contrato",
    subtipoDocumental: "25",
    colecao: "Y",
    classe: "X",
    subclasse: "Z",
  },
  {
    key: 26,
    titulo: "Capítulo 26",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "26",
    colecao: "Z",
    classe: "Y",
    subclasse: "W",
  },
  {
    key: 27,
    titulo: "Livro 27",
    tipoDocumental: "Livro",
    subtipoDocumental: "27",
    colecao: "AA",
    classe: "Z",
    subclasse: "X",
  },
  {
    key: 28,
    titulo: "Contrato 28",
    tipoDocumental: "Contrato",
    subtipoDocumental: "28",
    colecao: "BB",
    classe: "W",
    subclasse: "Y",
  },
  {
    key: 29,
    titulo: "Capítulo 29",
    tipoDocumental: "Capítulo",
    subtipoDocumental: "29",
    colecao: "CC",
    classe: "X",
    subclasse: "Z",
  },
  {
    key: 30,
    titulo: "Livro 30",
    tipoDocumental: "Livro",
    subtipoDocumental: "30",
    colecao: "DD",
    classe: "Y",
    subclasse: "W",
  },
];
